# -*- coding: utf-8 -*-
"""Mall_Customer_Segmentation_old.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZlGGdzqX0oaL55AYCbRoshijWGXMsjV5
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# clustering algorithms
from sklearn.cluster import KMeans,AgglomerativeClustering
from sklearn.metrics import silhouette_samples, silhouette_score

# load dataset
customer_df = pd.read_csv("/content/Mall_Customers.csv")

customer_df.head()

customer_df.shape

customer_df.info()

customer_df.describe()

customer_dtype = customer_df.dtypes
customer_dtype.value_counts()

customer_df.isnull().sum()

sns.countplot(customer_df['Gender'])

plt.show()

sns.distplot(customer_df['Age'])

sns.distplot(customer_df['Annual Income (k$)'])

sns.distplot(customer_df['Spending Score (1-100)'])

# scatter plot
sns.scatterplot(x=customer_df['Annual Income (k$)'],
                y=customer_df['Spending Score (1-100)'])

#Pairplot
sns.pairplot(customer_df, vars=["Age", "Annual Income (k$)", "Spending Score (1-100)"],  kind ="reg", hue = "Gender", palette="husl", markers = ['o','D'])

customer_df.drop(columns='CustomerID',axis=1,inplace=True)

from sklearn.preprocessing import LabelEncoder
# Create an instance of the LabelEncoder class
le = LabelEncoder()
# Get a list of categorical columns
categorical_cols = customer_df.select_dtypes(include='object').columns
# Apply the label encoder to each categorical column
for col in categorical_cols:
    customer_df[col] = le.fit_transform(customer_df[col])

customer_df.info()

corr = customer_df.corr()
sns.heatmap(corr, annot=True, cmap='rainbow')

# select the features
X = customer_df
#Scaling Data
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
X = scaler.fit_transform(X)

X

from sklearn.cluster import KMeans

inertia = []
range_val = range(1,17)
for i in range_val:
  kmean = KMeans(n_clusters=i,init='k-means++',random_state=3)
  kmean.fit_predict(pd.DataFrame(X))
  inertia.append(kmean.inertia_)
plt.plot(range_val,inertia,'go-')
plt.xlabel('Values of K')
plt.ylabel('Inertia')
plt.title('The Elbow Method using Inertia')
plt.show()

# Silhouette score analysis to find the ideal number of clusters for K-means clustering

range_n_clusters = [2, 3, 4, 5, 6, 7]

for num_clusters in range_n_clusters:

        # intialise kmeans
        kmeans = KMeans(n_clusters=num_clusters, max_iter=50,random_state=126)
        kmeans.fit(X)

        cluster_labels = kmeans.labels_

        # silhouette score
        silhouette_avg = silhouette_score(X, cluster_labels)
        print("For n_clusters={0}, the silhouette score is {1}".format(num_clusters, silhouette_avg))

# apply kmeans algorithm
kmeans_model=KMeans(5)
kmeans_clusters = kmeans_model.fit_predict(X)

import scipy.cluster.hierarchy as sch
plt.figure(figsize=(10, 7))
plt.title("Customer Dendograms")
dend = sch.dendrogram(sch.linkage(X, method='ward'))

# apply agglomerative algorithm
agglo_model = AgglomerativeClustering(linkage="ward",n_clusters=5)
agglomerative_clusters = agglo_model.fit_predict(X)

agglomerative_clusters

def silhouette_method(df,algo,y_pred):
    print('=================================================================================')
    print('Clustering ',algo," : silhouette score : ",silhouette_score(df,y_pred) )


silhouette_method(X,' : KMeans',kmeans_clusters)
silhouette_method(X,' : Agglomerative',agglomerative_clusters)


print('=================================================================================')

# add the cluster predictions to the dataframe
customer_df['cluster'] = kmeans_clusters
# display the first 5 rows of the dataframe with the cluster predictions
print(customer_df.head())

# Scatter plot on Original attributes to visualize the spread of the data
sns.scatterplot(x='Annual Income (k$)', y='Spending Score (1-100)', hue='cluster', data=customer_df, palette="deep")
# add a title and labels to the plot
plt.title('Clusters of Customers')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
# show the plot
plt.show()

# create a scatter plot of the data with different colors for each cluster
sns.scatterplot(x='Annual Income (k$)', y='Spending Score (1-100)', hue='cluster', data=customer_df, palette="deep")
# add a title and labels to the plot
plt.title('Clusters of Customers')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Gender')
# show the plot
plt.show()

# create a scatter plot of the data with different colors for each cluster
sns.scatterplot(x='Annual Income (k$)', y='Spending Score (1-100)', hue='cluster', data=customer_df, palette="deep")
# add a title and labels to the plot
plt.title('Clusters of Customers')
plt.xlabel('Age)')
plt.ylabel('Gender')
# show the plot
plt.show()

# create a scatter plot of the data with different colors for each cluster
sns.scatterplot(x='Annual Income (k$)', y='Spending Score (1-100)', hue='cluster', data=customer_df, palette="deep")
# add a title and labels to the plot
plt.title('Clusters of Customers')
plt.xlabel('Age)')
plt.ylabel('Gender')
# show the plot
plt.show()